general {
    lock_cmd = swaylock -f -c 000000        
    before_sleep_cmd = loginctl lock-session  
    ignore_dbus_inhibit = false 
}

listener {
    timeout = 500                            
    on-timeout = loginctl lock-session 
}

listener {
    timeout = 800                          
    on-timeout = loginctl lock-session; hyprctl dispatch dpms off 
    on-resume = hyprctl dispatch dpms on
}
